### ISSUE TITLE
Add nests JSON and schema

### ISSUE THREAD

**Issue by floogulinc** [mn-pollinators/assets#10]

**Comment by carl5004** [comment]
What information do we want for nests? At least a name, art image, and what bees use the nest, right? 

Are we going to have information cards about the nests? If so, I think I might include a photographic image (with the corresponding file name, attribution, caption, and image link) and a description. But do we really need those if the nests are just going to serve as "home base"? 

What do you think @floogulinc and @kklamberty ?

**Comment by kklamberty** [comment]
I think it makes sense to have photos. I think there may be times that a bee is inactive and a learner may wish to explore their nest a little bit.

**Comment by floogulinc** [comment]
I don't think we need which bees use each nest since that is already part of each bee in the bees json
