### ISSUE TITLE
Bees have accepted_flowers that don't exist in flowers.json

### ISSUE THREAD

**Issue by floogulinc** [mn-pollinators/assets#17]
As we were working on importing the JSON data into Buzz About we ran into an issue where as we are trying to associate a bee's accepted flowers with flowers from the flowers JSON. There are flowers listed in the bee's `accepted_flowers` that don't exist in the flowers JSON.

We currently have implemented a filter to just ignore those cases but maybe we want to remove them here and enforce through an automated script that all the bee's accepted flowers should exist in the flowers JSON.

**Comment by kklamberty** [comment]
@carl5004 - What do you think about this issue? One reason to remove the flowers from a list of `accepted_flowers`: we don't have any data on those flowers (even the name). Is it the case that we should add that flower data or is it the case that we should remove the flower from bees' lists? Thanks!

**Comment by carl5004** [comment]
Is there a specific example of this? -- I believe I must have made a mistake - I intended for any flower listed in the bee's `accepted_flowers` to be in the flowers.json data. I would like it to be added, but I'd like to see what those listed flowers are before I make a firm decision.
