### ISSUE TITLE
License for Artistic Contributions

### ISSUE THREAD

**Issue by carl5004** [mn-pollinators/assets#6]
Once art is added to this repository we'll want to make sure it has the correct license/copyright information. Maybe add copyright info to the README and/or updating the LICENSE? We may potentially want to find similar repositories on GitHub that handle different assets

**Comment by kklamberty** [comment]
For illustrations made by @carl5004 , we will refer to whichever license she chooses and explain where those illustrations are located. For the images sourced elsewhere, we will want to mention the files that contain the appropriate licenses for those images. We think that may be enough, but more research could still be useful.

**Comment by carl5004** [comment]
I believe we ended up agreeing on **Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)** for my illustrations. 

I have found a couple of examples of github pages that clarify between MIT licenses and other parts or assets that are different. 

[Artsy GitHub](https://github.com/artsy/artsy.github.io) 
-Explains in the README that the code is released under the MIT license but the contents of the blog itself (and they say specifically the contents of the `_posts` directory) is released under a Creative Commons license.

[TEAMarg Arduventure](https://github.com/TEAMarg/ID-46-Arduventure)
-This project is a game (so is a more comparable example to our project). The code is licensed under MIT but the "story, characters, sprites, tiles, design and art" are copyrighted to TEAM a.r.g. It says this explicitly in both the README and LICENSE files.
-There is also an interesting discussion about the implications of that decision [here](https://github.com/TEAMarg/ID-46-Arduventure/issues/1).

**Comment by carl5004** [comment]
At our virtual group meeting on 6/1/2020, we agreed that the above-mentioned Artsy GitHub is close to what we are looking for in terms of directory set-up and description for license clarification. 

I believe this will mean that in the README.md file (in all the repos) there will be a header that says "License" that will say, 

> "The code in this repository is released under the MIT license. The illustrations themselves are released under +Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0). Other photographs or images are released under their own listed attributions."

The actual LICENSE file will only describe the MIT license.

@kklamberty Is this an appropriate description? What would you add? Does this seem accurate to what we discussed?

**Comment by kklamberty** [comment]
I think that this text looks fine, but I think this is where you would also want to actually give attribution. Something like "The illustrations themselves are released by Olivia Carlson under..." or, maybe you have seen an example that words it differently. Thoughts, @carl5004 ?

**Comment by carl5004** [comment]
> I think that this text looks fine, but I think this is where you would also want to actually give attribution. Something like "The illustrations themselves are released by Olivia Carlson under..." or, maybe you have seen an example that words it differently. Thoughts, @carl5004 ?

I think you suggestion looks good. Should I add this to the files then?

**Comment by kklamberty** [comment]
> I think your suggestion looks good. Should I add this to the files then?

Yes, I think that's a good plan.
